name: Project Eq08 CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Style
        run: mvn git-code-format:validate-code-format
      - name: Tests
        run: mvn test && mvn jacoco:report
      - name: Code Coverage
        uses: codecov/codecov-action@v1
        run: mvn jacoco:report
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: ./codecov.yml
