name: Airbnb integration tests
on:
  push:
    branches:
      - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Integration tests
        uses: matt-ball/newman-action@master
        with:
          collection: resources/integrationTests.json
          environment: resources/integrationTestsEnv.json
