name: Airbnb integration tests
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@master
      - name: Integration tests
        with:
          collection: resources/integrationTests.json
          environment: resources/integrationTestsEnv.json
